### ISSUE TITLE
Erreur dans les logs

### ISSUE THREAD

**Issue by landaisbenj** [saniho/apiEnedis#111]
Hello. J'ai eu une eu erreur dans les logs. Je ne sais pas trop comment avoir plus d'info, mais voici le resultat :)

```
2022-01-20 11:26:09 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2022-01-20 11:26:41 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2022-01-20 11:27:12 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout

2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] 09145007157315 - last call : updateYesterday
2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] myEnedis ...09145007157315 update termine, on retentera plus tard(B)
2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] ------------------------------------------------------------

2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] Erreur inconnue call ERROR local variable 'error' referenced before assignment
2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] Erreur last answer local variable 'error' referenced before assignment
2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] Erreur last call updateYesterday
2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] Erreur last answer {'enedis_return': {'error': 'UNKERROR_TIMEOUT', 'message': 'Timeout'}}

2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 764, in update
    self.updateYesterday()
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 501, in updateYesterday
    data = self._yesterday.updateData(clefFunction, self.getHorairePossible(), data, deb, fin, withControl=withControl, dataControl = requestJson)
  File "/config/custom_components/myEnedis/myDataEnedis.py", line 77, in updateData
    self._data, callDone = self.CallgetData(dateDeb, dateFin)
  File "/config/custom_components/myEnedis/myDataEnedis.py", line 37, in CallgetData
    val1, val2 = self.myCalli.getDataPeriod(dateDeb, dateFin)
  File "/config/custom_components/myEnedis/myCall.py", line 106, in getDataPeriod
    dataAnswer = self.post_and_get_json(self._serverName, data=payload, headers=headers)
  File "/config/custom_components/myEnedis/myCall.py", line 93, in post_and_get_json
    raise error
UnboundLocalError: local variable 'error' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 835, in update
    raise Exception(inst)
Exception: local variable 'error' referenced before assignment

2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] ------------------------------------------------------------
2022-01-20 11:27:42 WARNING (SyncWorker_10) [myEnedis] (<class 'Exception'>, Exception(UnboundLocalError("local variable 'error' referenced before assignment")), <traceback object at 0xffff9b2c84c0>)
2022-01-20 11:27:42 ERROR (SyncWorker_10) [myEnedis] LastMethodCall : updateYesterday
```

**Comment by WarC0zes** [comment]
Pareille, depuis ce matin. Même erreur.

**Comment by saniho** [comment]
Hello oui, mais il ne devrait pas y avoir l'erreur... Vous avez quelle version ?

**Comment by landaisbenj** [comment]
1.3.2.7. Ca me dit qu'il y a une limite, mais je ne sais pas pourquoi elle est atteinte.

D'ailleurs, ca m'a retiré toutes les valeurs aussi, alors que je les avait hier, c'est etonnant qu'elles ne soient pas enregistrées...

**Comment by landaisbenj** [comment]
Et j'ai des nouveaux logs aussi : 

```

2022-01-20 14:22:53 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2022-01-20 14:22:53 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'dt88EqGrX0NHE8wj9tfeSfxlJIE27yLBm0tJQbnMhAfIUAdNrzq6Xg', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '1.3.2.7'} 
2022-01-20 14:22:53 ERROR (SyncWorker_4) [myEnedis] params : None 
2022-01-20 14:22:53 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_production", "usage_point_id": "09145007157315", "start": "2022-01-19", "end": "2022-01-20"} 
2022-01-20 14:22:53 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"tag":"limit_reached","error_code":500,"description":" Limite de 50 demandes par jour atteinte. Merci de mettre à jour vos intégrations afin de réduire  le nombre de demandes par jour","alert_user":true,"enedis_return":false,"support":"https://discord.gg/DfVJZme"} 
2022-01-20 14:22:53 ERROR (SyncWorker_4) [myEnedis] ************************************************************
```

**Comment by saniho** [comment]
le probleme se produit en effet avec la prerelease 1.4.0.1
je livre un correctif d'ici quelques minutes version 1.4.0.2

**Comment by WarC0zes** [comment]
Ok, j'ai installer la 1.4.0.2 et j'attends les remontés de ce matin. Je te tient au courant.

**Comment by WarC0zes** [comment]
J'ai ces erreurs avec la 1.4.0.2 et rien n'est remonté.
```
2022-01-21 11:31:54 ERROR (SyncWorker_6) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2022-01-21 11:32:25 ERROR (SyncWorker_6) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2022-01-21 11:32:55 ERROR (SyncWorker_6) [myEnedis] **************** - last call : updateLast7DaysDetails
2022-01-21 11:32:55 ERROR (SyncWorker_6) [myEnedis] myEnedis ...**************** update termine, on retentera plus tard(B)
2022-01-21 11:32:55 ERROR (SyncWorker_6) [myEnedis] ------------------------------------------------------------
2022-01-21 11:32:55 ERROR (SyncWorker_6) [myEnedis] Erreur inconnue call ERROR 'meter_reading'
2022-01-21 11:32:55 ERROR (SyncWorker_6) [myEnedis] Erreur last answer 'meter_reading'
2022-01-21 11:32:55 ERROR (SyncWorker_6) [myEnedis] Erreur last call updateLast7DaysDetails
2022-01-21 11:32:55 ERROR (SyncWorker_6) [myEnedis] Erreur last answer {'enedis_return': {'error': 'UNKERROR_TIMEOUT', 'message': 'Timeout'}}
2022-01-21 11:32:56 ERROR (SyncWorker_6) [myEnedis] Traceback (most recent call last):
File "/config/custom_components/myEnedis/myClientEnedis.py", line 774, in update
self.updateLast7DaysDetails()
File "/config/custom_components/myEnedis/myClientEnedis.py", line 336, in updateLast7DaysDetails
data = self._last7DaysDetails.updateData(clefFunction, self.getHorairePossible(), data, deb, fin, withControl=withControl, dataControl = requestJson)
File "/config/custom_components/myEnedis/myDataEnedisByDayDetail.py", line 108, in updateData
self._joursHC, self._joursHP = self.createMultiDaysHCHP(self._data)
File "/config/custom_components/myEnedis/myDataEnedisByDayDetail.py", line 147, in createMultiDaysHCHP
for x in data["meter_reading"]["interval_reading"]:
KeyError: 'meter_reading'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/myEnedis/myClientEnedis.py", line 846, in update
raise Exception(inst)
Exception: 'meter_reading'
2022-01-21 11:32:56 ERROR (SyncWorker_6) [myEnedis] ------------------------------------------------------------
2022-01-21 11:32:56 WARNING (SyncWorker_6) [myEnedis] (<class 'Exception'>, Exception(KeyError('meter_reading')), <traceback object at 0x7f91752440>)
2022-01-21 11:32:56 ERROR (SyncWorker_6) [myEnedis] LastMethodCall : updateLast7DaysDetails
```

**Comment by mdeweerd** [comment]
Suite au constat de cette erreur dans la trace, j'ai fait un fork ou j'ai ajouté une action github pour vérifier le python.

Cela identifie d'autres problèmes potentielles - notamment l'utilisation d'eval pour décoder le json.  

Je ne propose pas de pull request, mais vous pouvez toujours le récupérer si vous voulez.

Exemple de messages:
https://github.com/mdeweerd/apiEnedis/runs/4908136407?check_suite_focus=true

**Comment by WarC0zes** [comment]
j'ai eu les remontés aujourd'hui 👍.
Voici les logs avec la 1.4.0.3:
```
2022-01-24 12:16:58 ERROR (SyncWorker_8) [myEnedis] ************************************************************
2022-01-24 12:16:58 ERROR (SyncWorker_8) [myEnedis] header : {'Authorization': 'oEjtN0gOVZXW3QeHi76567YlZYeqLNc1gjKlPwlAOtxaqYwfso7qDk', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '1.4.0.3'}
2022-01-24 12:16:58 ERROR (SyncWorker_8) [myEnedis] params : None
2022-01-24 12:16:58 ERROR (SyncWorker_8) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "**************", "start": "2022-01-23", "end": "2022-01-24"}
2022-01-24 12:16:58 ERROR (SyncWorker_8) [myEnedis] Error JSON : {"usage_point_id":"**************","error":"token_refresh_401","description":"Une erreur est survenue, merci de renouveller vos consentements.","user_alert":true}
2022-01-24 12:16:58 ERROR (SyncWorker_8) [myEnedis] ************************************************************
``` 
Je comprends pas c'est erreur `"token_refresh_401","description":"Une erreur est survenue, merci de renouveller vos consentements."`
Ca serai du a quoi?

**Comment by saniho** [comment]
souvent cela est du à un probleme sur la gateway, et cela rien quelques jours plus tard... Sinon, c'est que le consentement a eut lieu il y a plus d'un an et qu'il faut le refaire.

**Comment by mdeweerd** [comment]
J'ai aussi des fois cette erreur et puis cela revient.

Pour le consentement: peut-être une valeur à enregistrer dans l'état et un rappel à ajouter?

**Comment by WarC0zes** [comment]
C'est plutôt un problème du gateway, car j'ai fait le consentement il y a 3 mois.

**Comment by saniho** [comment]
@mdeweerd comment se passe tes ajustements ? arrives-tu à merge sur la branche /dev ? comment s'organise-t-on pour la pre-release ?

**Comment by mdeweerd** [comment]
@saniho Apparemment tu n'a pas vu mon (message dans une des PR)[https://github.com/saniho/apiEnedis/pull/113#issuecomment-1020643749].  Les modifs sont faites.  
En somme, je te laisses regarder et merger la branche 'shortenLines' - d'une part cela permet de voir le type de modifs, et d'autre part de l'accepter ou pas.

**Comment by saniho** [comment]
en effet, j'avais pas vu, hesite pas à lancer la merge, comme cela j'ai juste à la revoir et l'approuver

**Comment by saniho** [comment]
j'ai livré une pre-release avec ta livraison : 1.4.0.4a

**Comment by mdeweerd** [comment]
@saniho Ok, j'ai récupéré ça sur mon système 

Concernant ceci:
```
Error JSON : {"usage_point_id":"xxxxx","error":"token_refresh_401","description":"Une erreur est survenue, merci de renouveller vos consentements.","user_alert":true}
```
Le `token_refresh_401` c'est une erreur pour le token entre la gateway et ENEDIS ou autre?  
C'est peut-être un token à renouveller entre la gateway et ENEDIS (automatiquement, il y a pas mal de services qui fournissent un token qui reste valide une durée limitée).

**Comment by saniho** [comment]
en effet c'est une erreur entre la gateway et enedis, j'ai deja echangé avec l'auteur de la gateway, mais il n'avais pas trouvé....cela revient plus tard( +24h souvent ), comme si cétait un soucis plutot coté Enedis

**Comment by mdeweerd** [comment]
Ok, je penche plutôt pour un problème côté GW puisqu'Enedis échange aussi avec des gros fournisseurs ...

**Comment by WarC0zes** [comment]
La version 1.4.0.4a fonctionne bien et les logs sont simple :) 
```
2022-01-28 11:40:56 ERROR (SyncWorker_8) [myEnedis] ************************************************************
2022-01-28 11:40:56 ERROR (SyncWorker_8) [myEnedis] header : {'Authorization': 'oEjtN0gOVZXW3QeHi76567YlZYeqLNc1gjKlPwlAOtxaqYwfso7qDk', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '1.4.0.4'}
2022-01-28 11:40:56 ERROR (SyncWorker_8) [myEnedis] params : None
2022-01-28 11:40:56 ERROR (SyncWorker_8) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "*****************", "start": "2022-01-27", "end": "2022-01-28"}
2022-01-28 11:40:56 ERROR (SyncWorker_8) [myEnedis] Error JSON : {"usage_point_id":"*************","error":"token_refresh_401","description":"Une erreur est survenue, merci de renouveller vos consentements.","user_alert":true}
2022-01-28 11:40:56 ERROR (SyncWorker_8) [myEnedis] ************************************************************
```
Il y a toujours l'erreur "token_refresh_401" mais pas gênant en soit.

Par contre il y a un problème sur le pourcentage du jours, car j'ai bien les infos remonté mais le calcul se fait pas. Ca reste sur -100%
![linky jours](https://user-images.githubusercontent.com/91471397/151537889-e648d3ec-eefb-4933-9fd8-1c7b33ea6996.jpg)

**Comment by saniho** [comment]
je penses savoir pourquoi ... en fait parfois le hier de enedis ne retourne rien, et donc j'utilise le hier sur les 7 derniers jours ... sauf que le ratio doit pas bien gerer ce changement ....

**Comment by kevincaradant** [comment]
> en effet c'est une erreur entre la gateway et enedis, j'ai deja echangé avec l'auteur de la gateway, mais il n'avais pas trouvé....cela revient plus tard( +24h souvent ), comme si cétait un soucis plutot coté Enedis

Je pense aussi car lorsque j'allais sur Enedis hier ou avant hier, il y avait écrit de mémoire  "merci de revenir ultérieurement, un problème est survenu"  bref je ne pouvais même pas accéder à l'interface Enedis de mon compteur meme si maintenant je peux mais j'ai encore l'erreur sous HA." 

Petite question aussi @saniho , est-ce qu'il est possible de mettre en "info" ou "warning" plutot que "error" tes logs car dans HA ca pollue pas mal la console de log :D 

![image](https://user-images.githubusercontent.com/6093175/152567832-4ff01bd6-08ca-47c4-8047-c92b1f66744a.png)

**Comment by saniho** [comment]
pour moi, il s'agit d'erreur .. et donc normal que cela en log.error
mais je suis à l'ecoute d'avis complémetaire

**Comment by kevincaradant** [comment]
> pour moi, il s'agit d'erreur .. et donc normal que cela en log.error mais je suis à l'ecoute d'avis complémetaire

Je n'ai pas de solution dans l'immediat c'est juste trop détaillé, ca prend trop de place sur al console d'erreur de HA et il m'est arrivé de rater des logs provenant d'autres erreurs ;). 
Cela m'a aussi été remonté par des amis qui utilisent ton plugin. Je suis assez d'accord sur ces points.
Je suis aussi d'accord que ce sont des erreurs mais elles surviennent souvent, il serait judicieux d'"avoir qu'une ligne ou 2 si tu peux, éviter les -------------------- ou **************************** ou fusioner les 3 erreurs en 1 peut etre ? :)

**Comment by saniho** [comment]
@kevincaradant merci pour les remarques
peux-tu tester avec la pre-derniere release [1.4.1.0](https://github.com/saniho/apiEnedis/releases/tag/1.4.1.0) et voir si c'est mieux ?

**Comment by mdeweerd** [comment]
Peut-être envoyer les messages d'un appel vers un fichier dans le répertoire du composant, et y faire référence dans la trace.

**Comment by WarC0zes** [comment]
Sur la version 1.5.1 j'ai c'est nouvelle erreur dans les logs

```
Logger: myEnedis
Source: custom_components/myEnedis/myClientEnedis.py:249
Integration: MyEnedis ([documentation](https://github.com/saniho/apiEnedis/), [issues](https://github.com/saniho/apiEnedis/issues))
First occurred: 10:22:41 (1 occurrences)
Last logged: 10:22:41

>>>> erreur ecriture : /config/custom_components/archive/myEnedis/**************/updateYesterdayProduction.json / {'tag': 'enedis_return_ko', 'error_code': 'ADAM-ERR0069', 'description': 'Le sens de la mesure ne correspond pas pour le PRM demandé', 'alert_user': True, 'enedis_return': True, 'support': 'https://discord.gg/DfVJZme'}

**Comment by mdeweerd** [comment]
Le répertoire `config/custom_components/archive/myEnedis/**************` existe? - normalement il est créé.

Ceci dit, j'ai un test qui fait qqchse de similaire quand il est exécuté sur github, mais qui fonctionne en local.  Avec un peu de chance la cause est la même et du coup ce n'est pas en soi lié à l'environnement de test github.

**Comment by WarC0zes** [comment]
Oui, le répertoire existe. le fichier aussi avec ca d'écrit dedans:

updateYesterdayProduction.json
```
{"tag": "limit_reached", "error_code": 500, "description": " Limite de 50 demandes par jour atteinte. Merci de mettre \u00e0 jour vos int\u00e9grations afin de r\u00e9duire  le nombre de demandes par jour", "alert_user": true, "enedis_return": false, "support": "https://discord.gg/DfVJZme"}
```

**Comment by WarC0zes** [comment]
Oui, pas de soucis.
