### ISSUE TITLE
Erreur lors du test de check config

### ISSUE THREAD

**Issue by aladin2000** [saniho/apiEnedis#20]
je suis dans la dernière version de HA : 2020.12.1

et je rencontre le probleme lors du demarrage de HA et lors du checkconfig 
à propos du module messages 
j'ai fais un pip3 install messages  mais sans resultat probant : voici la trace au démarrage   tu as une idée  de la cause ?

---------------------------------------------------------
2020-12-27 15:48:03 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/config/custom_components/apiEnedis/myEnedis.py", line 6, in <module>
    from . import  messages
ImportError: cannot import name 'messages' from partially initialized module 'custom_components.apiEnedis' (most likely due to a circular import) (/config/custom_components/apiEnedis/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 823, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 424, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 429, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/apiEnedis/__init__.py", line 17, in <module>
    from . import myEnedis
  File "/config/custom_components/apiEnedis/myEnedis.py", line 8, in <module>
    import messages
ModuleNotFoundError: No module named 'messages'
pi@rasp-remy:/usr/share/hassio/homeassistant $

**Comment by saniho** [comment]
as-tu bien pris la version alpha : https://github.com/saniho/apiEnedis/tree/V1.1.0.0alpha/custom_components/apiEnedis

**Comment by aladin2000** [comment]
Pas sûr
Je vai la re
tester

Merci

27 déc. 2020 22:40:02 saniho <notifications@github.com>:

**Comment by saniho** [comment]
^peux-tu me faire une copie d'ecran de ce repertoire : 
\config\custom_components\myEnedis
voici mon contenu, tu devrais avoir le meme : 
![image](https://user-images.githubusercontent.com/52693545/103240341-5eb40700-4950-11eb-9810-e7e949690626.png)

**Comment by aladin2000** [comment]
J'ai refais l'installation depuis hacs et. L'erreur a disparu
Remarque je vais faire pareil avec le plugin
Question: j'ai une offre edf bleu,blanc,rouge 
Est ce que tu pourrais me dire si ton api prend en charge ou non 
Si oui comment paramétrer ,?
Merci d'avance pour tout

**Comment by aladin2000** [comment]
Merci
