### ISSUE TITLE
Detected blocking call to putrequest inside the event loop.

### ISSUE THREAD

**Issue by flouck** [saniho/apiEnedis#201]
Voici le log :
```
Logger: homeassistant.util.async_
Source: util/async_.py:180
First occurred: 10:27:08 PM (1 occurrences)
Last logged: 10:27:08 PM

Detected blocking call to putrequest inside the event loop. This is causing stability issues. Please report issue to the custom integration author for myEnedis doing blocking calls at custom_components/myEnedis/gitinformation.py, line 37: myURL = urlopen(self._serverName)
```

**Comment by flouck** [comment]
And here is another error linked to MyEnedis which comes all the time:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/myEnedis/sensorEnedis.py:116
Integration: MyEnedis (documentation, issues)
First occurred: 1:36:11 PM (2 occurrences)
Last logged: 1:38:11 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 83, in _async_update
    self._update_state()
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 114, in _update_state
    status_counts, state = self._myDataSensorEnedis.getStatus(self._typeSensor)
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 198, in getStatus
    status["versionUpdateAvailable"] = self.getExistsRecentVersion(
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 116, in getExistsRecentVersion
    gitVersionObj = packaging.version.parse(versionGit)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
```

**Comment by flouck** [comment]
Hey Saniho, comment forcer la mise à jour vers cette version pour le test ? HACS ne le propose pas.

Mathieu
________________________________

**Comment by flouck** [comment]
J'ai trouvé. J'ai mis à jour puis redémarré. Voici les deux erreurs logs


```
This error originated from a custom integration.

Logger: myEnedis
Source: custom_components/myEnedis/myCall.py:292
Integration: MyEnedis (documentation, issues)
First occurred: 11:14:38 PM (8 occurrences)
Last logged: 11:14:38 PM

header : {'Authorization': 'xx', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.0.3'}
params : None
data : {"type": "daily_consumption", "usage_point_id": "xx", "start": "2021-12-14", "end": "2021-12-15"}
Error JSON : {"tag":"enedis_return_ko","error_code":"no_data_found","description":"no measure found for this usage point","alert_user":true,"enedis_return":true,"support":"https://discord.gg/DfVJZme"}
Data answer: {'tag': 'enedis_return_ko', 'error_code': 'no_data_found', 'description': 'no measure found for this usage point', 'alert_user': True, 'enedis_return': True, 'support': 'https://discord.gg/DfVJZme'}
```

Et

```
This error originated from a custom integration.

Logger: myEnedis
Source: custom_components/myEnedis/myClientEnedis.py:280
Integration: MyEnedis (documentation, issues)
First occurred: 11:14:38 PM (3 occurrences)
Last logged: 11:14:38 PM

Xx - Erreur call ERROR ('call', 'error', 'Collecte de données non activée sur le site enedis.fr')
Xx - last call : updateYesterdayLastYear
myEnedis ...xx update termine, on retentera plus tard(A1)

```

Pourtant ça marchait il ya encore pas longtemps

**Comment by saniho** [comment]
peut-etre un renouvellement à faire .. car les premiers retours user montrent que tout fonctionne
