### ISSUE TITLE
invalid version returned in HA

### ISSUE THREAD

**Issue by totoantibes** [saniho/apiEnedis#203]
here is the log of the error i get in HA Core.
used to work fine until i redid the consent on myelectricaldata. 

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/myEnedis/sensorEnedis.py:115
Integration: MyEnedis (documentation, issues)
First occurred: 12:40:05 AM (21 occurrences)
Last logged: 1:23:20 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 83, in _async_update
    self._update_state()
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 114, in _update_state
    status_counts, state = self._myDataSensorEnedis.getStatus(self._typeSensor)
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 198, in getStatus
    status["versionUpdateAvailable"] = self.getExistsRecentVersion(
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 115, in getExistsRecentVersion
    gitVersionObj = packaging.version.parse(versionGit)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''

**Comment by totoantibes** [comment]
same as issue:#200
