### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Fredzxda** [saniho/apiEnedis#206]
Bonjour,
Avec la version 1.5.1 comme 1.5.2 (beta), j'ai l'erreur suivante qui est levé par home assistant.
```
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant
Source: custom_components/myEnedis/sensorEnedis.py:116
Integration: MyEnedis (documentation, issues)
First occurred: 12:02:39 (2 occurrences)
Last logged: 12:03:09

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 83, in _async_update
    self._update_state()
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 114, in _update_state
    status_counts, state = self._myDataSensorEnedis.getStatus(self._typeSensor)
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 198, in getStatus
    status["versionUpdateAvailable"] = self.getExistsRecentVersion(
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 116, in getExistsRecentVersion
    gitVersionObj = packaging.version.parse(versionGit)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''

```
Du coup les sensors ne sont jamais disponibles. Une idée de ce que j'aurai mal fait ?

**Comment by Fredzxda** [comment]
Je viens d'installer la beta 2.0.3 sans changer la configuration. Plus d'erreur dans les logs. Ca semble provenir des derniers changements dans HA core qui sont pris en compte en 2.0.3.
Par contre, les data remontées sont à 0
![image](https://user-images.githubusercontent.com/37531742/208239289-133c1de9-05f1-4b83-b02a-4d4ae1721fab.png)

**Comment by Fredzxda** [comment]
Toujours pas de changement

**Comment by saniho** [comment]
idem aujourd'hui ? si oui, peux-tj me faire parvenir ton pdl et ton token par mail ?
