### ISSUE TITLE
Call Error 503

### ISSUE THREAD

**Issue by B4dC4rd** [saniho/apiEnedis#207]
Malgré que le test cURL fonctionne bien et em renvoie des donnees sur ma consomation, le sensor MyEnedis ne recupere que des valeures a zero.
J'ai essayé de re-installer, reconfigurer, re-démarrer  et re-faire le consentement en vain.
En activant le debug, je trouve dans le log  cette erreur a repetition:

Logger: myEnedis
Source: custom_components/myEnedis/myClientEnedis.py:278
Integration: myEnedis sensor ([documentation](https://github.com/saniho/apiEnedis/), [issues](https://github.com/saniho/apiEnedis/issues))
First occurred: 17:10:23 (18 occurrences)
Last logged: 22:21:45

211xxxxxxxx1119 - Erreur call ERROR ('call', 'error', 503)
211xxxxxxxx1119 - last call : updateYesterday
myEnedis ...211xxxxxxx1119 update termine, on retentera plus tard(A1)

**Comment by B4dC4rd** [comment]
I noticed that sometimes the cURL test responds with 401 on the initial request. Subsequent requests are ok. Maybe this is trowing the sensor off?

**Comment by Toukite** [comment]
Même problème de mon côté
Aucune trace dans les logs (alors qu'avant l'intégration était plutôt très verbeuse), mais là aucune erreur, le curl MyElectricalData fonctionne, token régénéré, dernières versions, etc ...
Et malgré tout le sensor est vide
![image](https://user-images.githubusercontent.com/42780622/208680301-5c223b25-74d2-4416-a5d5-c1c0feebca1f.png)

**Comment by saniho** [comment]
@Toukite , si tu peux tester avec la version 2.2.0-alpha ....

**Comment by Toukite** [comment]
Je viens de tester, et j'ai désormais un log error (toujours pas de data):

Logger: homeassistant.components.sensor
Source: custom_components/myEnedis/myEnedisSensorCoordinator.py:74
Integration: Sensor (documentation, issues)
First occurred: 11:28:07 PM (2 occurrences)
Last logged: 11:28:07 PM

Error adding entities for domain sensor with platform myEnedis
Error while setting up myEnedis platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 74, in state
    return self._state
AttributeError: 'myEnedisSensorCoordinator' object has no attribute '_state'


PS: j'ai également une proposition d'update bizarre sur la card, il me propose la 1.0.4.0-alpha alors que j'ai une version à priori supérieure installée (1.1.2)

**Comment by WarC0zes** [comment]
Même erreur après le passage en v2.2.0-beta.
```
2022-12-21 15:24:10.687 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform myEnedis
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/myEnedis/myEnedisSensorCoordinator.py", line 74, in state
return self._state
AttributeError: 'myEnedisSensorCoordinator' object has no attribute '_state'
```

@Toukite
Fait pas attention au numéro de version, mais c'est bien une maj pour ajouter la comparaison de l'année.

**Comment by WarC0zes** [comment]
Re,
après la maj du core 2022.12.8 et un reboot, j'ai le nouveau sensor de production qui a bien été créer et j'ai plus le message d'erreur. 
![production](https://user-images.githubusercontent.com/91471397/209045912-416a0102-8a3a-4607-8d51-5da2f9152407.png)

**Comment by Toukite** [comment]
De mon côté pas d'amélioration suite à l'upgrade en 2022.12.8 si ce n'est effectivement la disparition du log d'erreur.

@saniho as-tu des pistes ? sans aucune trace dans les logs je ne sais pas trop comment aider l'investigation

@WarC0zes ok, moi aussi j'ai ce sensor, mais le problème est sur le sensor principal à savoir  myEnedis.pdl, qui n'est alimenté que sur quelques attributs comme "Last month" ou "Last month last year" mais toutes les autres infos de consommation sont vides, ce qui fait que la card n'est remplie que de panneaux 
![image](https://user-images.githubusercontent.com/42780622/209092913-f67197d2-6477-4a93-9eb4-de9131234caf.png)

PS @saniho et est-ce que tu confirmes pour la version de la card ?

**Comment by Toukite** [comment]
@saniho peux-tu stp confirmer si sur la config de l'intégration nous devons mettre enedisGateway ou myElectricalData ? 
Je vois sur le screen de @WarC0zes qu'il est en enedisGateway alors que de mon côté j'ai changé pour myElectricalData
Aussi, pour le token, il faut bien utiliser celui de myElectricalData désormais ?

Cela pourrait expliquer le problème ?

**Comment by saniho** [comment]
possible, tout depend du provider utilisé
chacun à son token ....

**Comment by B4dC4rd** [comment]
Pour moi le probleme s'est resorbé suite aux mises-a-jour et au renouvellement du consentement.

**Comment by Toukite** [comment]
Oui c'est revenu pour moi aussi 🤷
