### ISSUE TITLE
GetStatusEcoWatt en erreur sur la version HA 2023.1.0

### ISSUE THREAD

**Issue by mplessis** [saniho/apiEnedis#218]
Bonjour,

lorsque la carte content-card-linky cherche a afficher les infos EcoWatt, une erreur se produit dans HA : 

```
2023-01-05 12:05:10.429 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinatorEcoWatt.py", line 75, in _async_update
    self._update_state()
  File "/config/custom_components/myEnedis/myEnedisSensorCoordinatorEcoWatt.py", line 106, in _update_state
    status_counts, state = self._myDataSensorEnedis.getStatusEcoWatt()
  File "/config/custom_components/myEnedis/sensorEnedis.py", line 150, in getStatusEcoWatt
    for maDate in self._myDataEnedis.getEcoWatt().getValue().keys():
AttributeError: 'int' object has no attribute 'keys'
```

Le rendu de la carte :

![error-ecowatt](https://user-images.githubusercontent.com/9799992/210767049-f67c8f31-1cff-4769-a817-2e3343af6eba.png)

Serveur HA : 2023.1.0
HA Operating system : 9.4
MyEnedis sensor : 2.3.0
Content-card-linky: 1.2.0

Merci à vous pour ces développements

**Comment by saniho** [comment]
@mplessis : peux-tu essayer avec la pre-release : v2.3.1-alpha

**Comment by mplessis** [comment]
Bonjour @saniho, alors je viens de regarder ce matin (pas eu de temps pour ça ce week-end désolé) et ça fonctionne maintenant en 2.3.0. Je vais tester la v2.3.1-alpha malgré tout et je te dis ce qu'il en est. Merci
