### ISSUE TITLE
Les données myenedis ne sont pas mise à jour

### ISSUE THREAD

**Issue by LGO44** [saniho/apiEnedis#224]
Suite au passage à myelectricaldata comme source de donnée pour myenedis j'obtiens le résultat suivant:

![image](https://user-images.githubusercontent.com/95585425/214838957-941707e9-94b6-4ea3-9c72-aa6a40c51fa1.png)

Les données myelectricaldata remontent bien
![image](https://user-images.githubusercontent.com/95585425/214839321-ab3acb0c-4e6c-49f8-a1c3-99585051d343.png)
 en utilisant :
_type: custom:content-card-linky
nbJoursAffichage: '7'
entity: sensor.myelectricaldata_consumption_142875__

avec myenedis 
![image](https://user-images.githubusercontent.com/95585425/214840136-2498d53b-7c42-41b1-a134-c2141364b0f7.png)

Malgré plusieurs désinstallations complètes de myenedis le problème persiste

**Comment by LGO44** [comment]
toujours pas de mise à jour des données 

erreur dans la variable myenedis
ErrorLastCall
('call', 'error', {'error_code': 'UNAVAILABLE', 'enedis_return': {'error': 'UNAVAILABLE', 'message': 'Indisponible, essayez plus tard'}})
ErrorLastCallInterne
('call', 'error', {'error_code': 'UNAVAILABLE', 'enedis_return': {'error': 'UNAVAILABLE', 'message': 'Indisponible, essayez plus tard'}})


extrait du fichier de logs:

2023-01-30 13:05:17.567 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #1 !!! requests.exceptions.Timeout
2023-01-30 13:05:17.682 ERROR (SyncWorker_4) [myEnedis] Data answer: {'enedis_return': {'error': 'UNKERROR_TIMEOUT', 'message': 'Timeout'}}
2023-01-30 13:06:47.795 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #2 !!! requests.exceptions.Timeout
2023-01-30 13:06:47.798 ERROR (SyncWorker_4) [myEnedis] Data answer: {'enedis_return': {'error': 'UNKERROR_TIMEOUT', 'message': 'Timeout'}}
2023-01-30 13:06:47.801 WARNING (SyncWorker_4) [myEnedis] Nombre d'appels à l'API dépassé, ou dernière erreur trop récente
2023-01-30 13:06:47.806 ERROR (SyncWorker_4) [myEnedis] myEnedis err ('call', 'error', {'error_code': 'UNAVAILABLE', 'enedis_return': {'error': 'UNAVAILABLE', 'message': 'Indisponible, essayez plus tard'}})
2023-01-30 13:06:47.807 ERROR (SyncWorker_4) [myEnedis] Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 271, in getData
    self.updateContract()
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 350, in updateContract
    data = self.contract.updateContract(indata)
  File "/config/custom_components/myEnedis/myContrat.py", line 96, in updateContract
    if self.__checkDataContract(data):
  File "/config/custom_components/myEnedis/myContrat.py", line 75, in __checkDataContract
    raise Exception("call", "error", dataAnswer)
Exception: ('call', 'error', {'error_code': 'UNAVAILABLE', 'enedis_return': {'error': 'UNAVAILABLE', 'message': 'Indisponible, essayez plus tard'}})

2023-01-30 13:06:47.810 ERROR (SyncWorker_4) [myEnedis] ------------------------------------------------------------
2023-01-30 13:06:47.812 WARNING (SyncWorker_4) [myEnedis] (<class 'Exception'>, Exception('call', 'error', {'error_code': 'UNAVAILABLE', 'enedis_return': {'error': 'UNAVAILABLE', 'message': 'Indisponible, essayez plus tard'}}), <traceback object at 0x7f3fb0bcc0>)
2023-01-30 13:06:47.813 ERROR (SyncWorker_4) [myEnedis] LastMethodCall : updateContract

**Comment by LGO44** [comment]
Un redémarrage home assistant et retour au point de départ.

**Comment by enzopanzani** [comment]
Bonjour LGO044, 
As-tu toujours la valeur "sensor.myenedis_cost-yestarday-XXX" en défaut? 
Je n'arrive pas à remonter cette valeur depuis plusieurs semaines. 
Merci :-)

**Comment by LGO44** [comment]
oui , c'est comme ça depuis le 24 janvier.
Depuis les variables myEnedis restent à 0 alors que myelectricaldata sont correctes.
MyEnedis renvoie systématiquement le nombre d'interrogation à 50 donc maxi....

**Comment by fana13** [comment]
@saniho tu as des news sur les problèmes de remontées des variables myEnedis ?
Les variables de myelectricaldata sont OK depuis quelques jours par contre côté myEnedis quasiment aucune variable ne fonctionne.
De mon côté je n'ai que les sensors ecowatt, et history_all qui remontent.

**Comment by LGO44** [comment]
Logs d'hier pour myEnedis

2023-02-22 10:21:42.522 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #1 !!! requests.exceptions.HTTPError
2023-02-22 10:21:42.525 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:21:42.529 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:21:42.531 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:21:42.533 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "1428", "start": "2023-02-21", "end": "2023-02-22"} 
2023-02-22 10:21:42.535 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:21:42.538 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:21:42.540 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:22:57.735 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #2 !!! requests.exceptions.HTTPError
2023-02-22 10:22:57.737 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:22:57.738 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:22:57.740 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:22:57.742 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "1428", "start": "2023-02-20", "end": "2023-02-22"} 
2023-02-22 10:22:57.744 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:22:57.746 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:22:57.747 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:24:55.088 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #3 !!! requests.exceptions.HTTPError
2023-02-22 10:24:55.097 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:24:55.100 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:24:55.102 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:24:55.108 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "1428", "start": "2023-02-15", "end": "2023-02-22"} 
2023-02-22 10:24:55.112 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:24:55.113 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:24:55.115 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:26:55.510 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #4 !!! requests.exceptions.HTTPError
2023-02-22 10:26:55.517 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:26:55.520 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:26:55.522 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:26:55.524 ERROR (SyncWorker_4) [myEnedis] data : {"type": "consumption_load_curve", "usage_point_id": "1428", "start": "2023-02-21", "end": "2023-02-22"} 
2023-02-22 10:26:55.526 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:26:55.529 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:26:55.531 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:27:51.533 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #5 !!! requests.exceptions.HTTPError
2023-02-22 10:27:51.537 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:27:51.541 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:27:51.542 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:27:51.545 ERROR (SyncWorker_4) [myEnedis] data : {"type": "consumption_load_curve", "usage_point_id": "1428", "start": "2023-02-15", "end": "2023-02-22"} 
2023-02-22 10:27:51.548 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:27:51.549 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:27:51.551 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:28:45.689 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #6 !!! requests.exceptions.HTTPError
2023-02-22 10:28:45.693 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:28:45.697 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:28:45.700 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:28:45.702 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "1428", "start": "2023-02-01", "end": "2023-02-22"} 
2023-02-22 10:28:45.704 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:28:45.706 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:28:45.709 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:30:46.316 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #7 !!! requests.exceptions.HTTPError
2023-02-22 10:30:46.320 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:30:46.325 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:30:46.327 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:30:46.330 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "1428", "start": "2023-01-01", "end": "2023-02-22"} 
2023-02-22 10:30:46.332 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:30:46.335 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:30:46.337 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:31:21.016 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #8 !!! requests.exceptions.HTTPError
2023-02-22 10:31:21.021 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:31:21.023 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:31:21.025 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:31:21.028 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "1428", "start": "2022-02-21", "end": "2022-02-22"} 
2023-02-22 10:31:21.030 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:31:21.033 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:31:21.035 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:32:57.289 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #9 !!! requests.exceptions.HTTPError
2023-02-22 10:32:57.292 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:32:57.295 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:32:57.297 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:32:57.299 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "1428", "start": "2022-02-21", "end": "2022-02-23"} 
2023-02-22 10:32:57.300 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:32:57.303 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:32:57.305 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:33:29.269 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #10 !!! requests.exceptions.HTTPError
2023-02-22 10:33:29.273 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:33:29.277 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:33:29.280 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:33:29.282 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_consumption_max_power", "usage_point_id": "1428", "start": "2023-02-21", "end": "2023-02-22"} 
2023-02-22 10:33:29.284 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:33:29.286 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:33:29.288 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:35:21.208 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #11 !!! requests.exceptions.HTTPError
2023-02-22 10:35:21.212 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:35:21.214 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:35:21.217 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:35:21.220 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "1428", "start": "2022-02-01", "end": "2022-02-22"} 
2023-02-22 10:35:21.232 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:35:21.234 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:35:21.235 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}
2023-02-22 10:36:48.429 ERROR (SyncWorker_4) [myEnedis] ====== Appel http #12 !!! requests.exceptions.HTTPError
2023-02-22 10:36:48.433 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:36:48.436 ERROR (SyncWorker_4) [myEnedis] header : {'Authorization': 'AkT0yOlEOI_RLR2zH', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2023-02-22 10:36:48.438 ERROR (SyncWorker_4) [myEnedis] params : None 
2023-02-22 10:36:48.440 ERROR (SyncWorker_4) [myEnedis] data : {"type": "daily_production", "usage_point_id": "1428", "start": "2023-02-21", "end": "2023-02-22"} 
2023-02-22 10:36:48.443 ERROR (SyncWorker_4) [myEnedis] Error JSON : {"detail":"Vous avez dépassé votre quota journalier (50)"} 
2023-02-22 10:36:48.445 ERROR (SyncWorker_4) [myEnedis] ************************************************************
2023-02-22 10:36:48.446 ERROR (SyncWorker_4) [myEnedis] Data answer: {'detail': 'Vous avez dépassé votre quota journalier (50)'}

**Comment by FRDev66** [comment]
Bonjour,

Je viens de faire l'installation et j'ai la même situation : aucune données ne remonte, toutes les courbes restent à 0 (sauf ecowatt sensor)

Avez-vous trouver une solution de votre côté ?
Faut-il attendre au moins 24h pour voir apparaître les premières remontées de données ?

:|

**Comment by saniho** [comment]
Je n'ai pas de soucis de mon coté. Es-ce que vous utilisé uniquement myEnedis ou en parallèle myelectricaldata ?
Car si c'est le cas, alors peut-etre que étant donné que vous partagez les accès, vous dépassez le nombre d'appels par jour.
Il faudrait desactiver 48h myelecctricalData pur voir si le problème perdure.

**Comment by saniho** [comment]
avez vous bien revalider la transmission des données ? Il y a une revalidation toutes les 12 mois mémoire
