### ISSUE TITLE
Erreur mise à jour données

### ISSUE THREAD

**Issue by LGO44** [saniho/apiEnedis#227]
Ci joints les logs myEnedis , données non mises à jour 

 2023-03-25 10:33:21.701 ERROR (SyncWorker_7) [myEnedis] 14881765491878 - last call : updateLastMonthLastYear
2023-03-25 10:33:21.727 ERROR (SyncWorker_7) [myEnedis] myEnedis ...14881765491878 update termine, on retentera plus tard(B)
2023-03-25 10:33:21.733 ERROR (SyncWorker_7) [myEnedis] ------------------------------------------------------------
2023-03-25 10:33:21.736 ERROR (SyncWorker_7) [myEnedis] Erreur inconnue call ERROR 'str' object has no attribute 'get'
2023-03-25 10:33:21.741 ERROR (SyncWorker_7) [myEnedis] Erreur last answer 'str' object has no attribute 'get'
2023-03-25 10:33:21.748 ERROR (SyncWorker_7) [myEnedis] Erreur last call updateLastMonthLastYear
2023-03-25 10:33:21.821 ERROR (SyncWorker_7) [myEnedis] Erreur last answer None
2023-03-25 10:33:21.919 ERROR (SyncWorker_7) [myEnedis] Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 1191, in update
    self.callConsommation()
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 1112, in callConsommation
    self.updateLastMonthLastYear()
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 553, in updateLastMonthLastYear
    data = self._lastMonthLastYear.updateData(
  File "/config/custom_components/myEnedis/myDataEnedisByDay.py", line 100, in updateData
    if (callDone) and (myCheckData().checkDataPeriod(self._data)):
  File "/config/custom_components/myEnedis/myCheckData.py", line 102, in checkDataPeriod
    if dataAnswer.get(API.ERROR_CODE, 200) == 500:
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 1284, in update
    raise Exception(inst)
Exception: 'str' object has no attribute 'get'

2023-03-25 10:33:21.939 ERROR (SyncWorker_7) [myEnedis] ------------------------------------------------------------
2023-03-25 10:33:21.964 WARNING (SyncWorker_7) [myEnedis] (<class 'Exception'>, Exception(AttributeError("'str' object has no attribute 'get'")), <traceback object at 0x7f651fa680>)
2023-03-25 10:33:21.976 ERROR (SyncWorker_7) [myEnedis] LastMethodCall : updateLastMonthLastYear

**Comment by saniho** [comment]
erreur gateway down
