### ISSUE TITLE
Installation Erreur

### ISSUE THREAD

**Issue by Shadorlo** [saniho/apiEnedis#237]
Bonjour, je possède ce message d'erreur lors de l'installation via HACS :

`Détails du journal (ERREUR)
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/base.py:450
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 22:04:51 (5 occurrences)
Last logged: 22:08:25

[546815572928] Error handling message: Unknown error (unknown_error) Tobias from 192.168.1.20 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0)
[546919731520] Error handling message: Unknown error (unknown_error) Tobias from 192.168.1.20 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 977, in async_install_repository
    await self.download_content(version_to_install)
  File "/config/custom_components/hacs/repositories/base.py", line 640, in download_content
    contents = self.gather_files_to_download()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/base.py", line 1175, in gather_files_to_download
    if self.should_try_releases:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/base.py", line 450, in should_try_releases
    if self.repository_manifest.filename.endswith(".zip"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'`

![image](https://github.com/saniho/apiEnedis/assets/50663301/52a08795-d1d1-4439-9320-ef7c497a51f9)
![image](https://github.com/saniho/apiEnedis/assets/50663301/7c1a5c1f-c352-4fc5-8aac-66deb28209a7)
![image](https://github.com/saniho/apiEnedis/assets/50663301/f260257d-1825-4f39-bfd5-20351819413e)

Merci et bonne soirée à vous :)

**Comment by Amaurgit** [comment]
La même ici 👍

**Comment by lesissou** [comment]
Pour moi aussi : impossible d'installer l'intégration

**Comment by cuty59** [comment]
Bonjour, meme probleme ici, version HA  2024.5.4

**Comment by steflrx** [comment]
👍Same with HA 2024.8.2 + HACS 2.0.0

**Comment by ioExpander** [comment]
A la mise à jour HA 2024.9.2. L'intégration s'est désinstallée et il est maintenant impossible de la ré-installer (HACS 2.x.x).
J'ai le même message d'erreur que celui sur cette issue.

Comment faire pour aider à débugger ?

**Comment by GhislainOlitec** [comment]
Malheureusement pareil ici :/ des infos ?

**Comment by baptiste-chailleux** [comment]
Même erreur chez moi avec HACS 2.0.1 & HA 2024.11.3. Dommage car l'intégration a l'air top.

**Comment by romsworld** [comment]
Meme pb pour moi

**Comment by mathieurag** [comment]
Idem pour moi ici ! Testé plusieurs releases sans succès, même erreur que remontée dans cette issue.

**Comment by ToXinE** [comment]
idem

**Comment by baptiste-chailleux** [comment]
Comme mentionné dans mon commentaire, l'installation en mode manuel fonctionne:

> Manuellement (à faire à chaque mise à jour)
> Dans votre propre dossier custom_components, créez un dossier nommé apiEnedis puis, copiez tout le contenu du dossier [apiEnedis](https://github.com/saniho/apiEnedis/tree/main/custom_components/apiEnedis) dedans.
> 
> Cliquez sur le bouton Redémarrer dans la zone Gestion du serveur

**Comment by Zeratyx** [comment]
Bonjour, 
Même message d'erreur pour l’installation à partir de HACS, et je ne souhaite pas passer par une installation en mode manuel.
Merci

**Comment by JonathannFrm** [comment]
Bonjour,
J'ai le même message en passant pas HACS, donc je fais la procédure manuelle. Sauf que je ne peux pas télécharger les fichiers (erreur ci dessous).
Du coup, je vois pas comment je peux faire maintenant.
Quelqu'un aurais une idée? Merci d'avance.

![Image](https://github.com/user-attachments/assets/92d8edb8-d7f1-4356-89d0-7c4069739667)

**Comment by JonathannFrm** [comment]
Je vais répondre à mon poste car j'ai trouver comment télécharger le dossier.
Il faut aller sur l'onglet Principale "Code" et télécharger tous le repos dans un ZIP

![Image](https://github.com/user-attachments/assets/81c511e7-dcda-4d60-af16-76cd12caaf8a)

Il suffit ensuite de récupérer le dossier souhaitais, dans ce ZIP.

**Comment by Vince1024** [comment]
Hi all,
Same error for me, did you find a solution as I can't use the integration anymore ?

![Image](https://github.com/user-attachments/assets/586174f0-a192-487c-90e4-2e9d1ffcd12e)

![Image](https://github.com/user-attachments/assets/d403438b-aae9-4ada-9c49-ce7809589fd3)

**Comment by Vince1024** [comment]
Bonjour à tous,

Désolé pour le précédent message en anglais...les habitudes son tenaces.

Pour ma part j'ai trouvé une solution qui fonctionne avec cet Add-on : 

https://github.com/bokub/ha-linky?tab=readme-ov-file#readme

Et en prime il récupère même les informations de consommation du passé, au top pour moi.

![Image](https://github.com/user-attachments/assets/65a06776-bd93-4ca6-bf0e-f3b8710147a1)
