### ISSUE TITLE
 myElectricalData et myEnedis Compteur incompatible 

### ISSUE THREAD

**Issue by Link0Darck** [saniho/apiEnedis#238]
Bonjour,
cela fait un moment je n'ai plus mes donné je suis dit si cela ce trouve il faut je fasse de nouveaux un demande de consentement sauf que cela ne fonctionne pas il me dit compteur incompatible il y a t'il une solution s'il vous plait merci d'avance

**Comment by Mikaaaeru** [comment]
Bonjour, je suis sur le même cas plus de valeur du jour au lendemain. Ça date de plusieurs semaines deja

**Comment by Link0Darck** [comment]
> Bonjour, je suis sur le même cas plus de valeur du jour au lendemain. Ça date de plusieurs semaines deja

Salut, ça va tu rassure je suis dit c'étais moi qui est fait une connerie

**Comment by Extreeeme** [comment]
Idem ici, plus de connexions depuis quelques jours sur l'intégration

```
2024-07-24 19:34:58.985 ERROR (SyncWorker_38) [myEnedis] ------------------------------------------------------------
2024-07-24 19:34:58.985 WARNING (SyncWorker_38) [myEnedis] (<class 'Exception'>, Exception(TypeError("string indices must be integers, not 'str'")), <traceback object at 0x7f34c29740>)
2024-07-24 19:34:58.985 ERROR (SyncWorker_38) [myEnedis] LastMethodCall : updateEcoWatt
2024-07-24 19:57:42.932 ERROR (SyncWorker_44) [myEnedis] ====== Appel http #46 !!! requests.exceptions.HTTPError
2024-07-24 19:57:42.932 ERROR (SyncWorker_44) [myEnedis] ************************************************************
2024-07-24 19:57:42.933 ERROR (SyncWorker_44) [myEnedis] header : {'Authorization': 'PWD', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '2.3.0'} 
2024-07-24 19:57:42.933 ERROR (SyncWorker_44) [myEnedis] params : None 
2024-07-24 19:57:42.934 ERROR (SyncWorker_44) [myEnedis] data : {"type": "rte/ecowatt", "usage_point_id": "ID", "start": "2024-07-23", "end": "2024-07-25"} 
2024-07-24 19:57:42.934 ERROR (SyncWorker_44) [myEnedis] Error JSON : {"detail":"Pas de données disponible entre la date du 2024-07-23 00:00:00 et 2024-07-25 00:00:00"} 
2024-07-24 19:57:42.934 ERROR (SyncWorker_44) [myEnedis] ************************************************************
2024-07-24 19:57:42.935 ERROR (SyncWorker_44) [myEnedis] Data answer: {'detail': 'Pas de données disponible entre la date du 2024-07-23 00:00:00 et 2024-07-25 00:00:00'}
2024-07-24 19:57:42.937 ERROR (SyncWorker_44) [myEnedis] ID- last call : updateEcoWatt
2024-07-24 19:57:42.938 ERROR (SyncWorker_44) [myEnedis] myEnedis ...ID update termine, on retentera plus tard(B)
2024-07-24 19:57:42.938 ERROR (SyncWorker_44) [myEnedis] ------------------------------------------------------------
2024-07-24 19:57:42.938 ERROR (SyncWorker_44) [myEnedis] Erreur inconnue call ERROR string indices must be integers, not 'str'
2024-07-24 19:57:42.939 ERROR (SyncWorker_44) [myEnedis] Erreur last answer string indices must be integers, not 'str'
2024-07-24 19:57:42.939 ERROR (SyncWorker_44) [myEnedis] Erreur last call updateEcoWatt
2024-07-24 19:57:42.940 ERROR (SyncWorker_44) [myEnedis] Erreur last answer {'detail': 'Pas de données disponible entre la date du 2024-07-23 00:00:00 et 2024-07-25 00:00:00'}
2024-07-24 19:57:42.944 ERROR (SyncWorker_44) [myEnedis] Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 1193, in update
    self.callEcoWatt()
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 1160, in callEcoWatt
    self.updateEcoWatt()
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 769, in updateEcoWatt
    data = self._ecoWatt.updateData(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myEnedis/myDataEnedisEcoWatt.py", line 92, in updateData
    self._value = myCheckData().analyseValueEcoWatt(self._data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myEnedis/myCheckData.py", line 52, in analyseValueEcoWatt
    for detailDate in data[date]["detail"]:
                      ~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 1284, in update
    raise Exception(inst)
Exception: string indices must be integers, not 'str'

2024-07-24 19:57:42.944 ERROR (SyncWorker_44) [myEnedis] ------------------------------------------------------------
2024-07-24 19:57:42.945 WARNING (SyncWorker_44) [myEnedis] (<class 'Exception'>, Exception(TypeError("string indices must be integers, not 'str'")), <traceback object at 0x7f34c46540>)
2024-07-24 19:57:42.945 ERROR (SyncWorker_44) [myEnedis] LastMethodCall : updateEcoWatt
```

**Comment by Mikaaaeru** [comment]
Alors après vérification sur myelecticaldata il semblerait que enedis soit en maintenance. Attendons de voir la suite

**Comment by Link0Darck** [comment]
Punaise quand il font une maintenance 22 jours ça pique mais oui pas le choix d'attendre.

**Comment by Extreeeme** [comment]
La maintenance semble être terminée de mon côté, j'ai du regénérer la clé de l'API tout de même

Toujours les erreurs "habituelles" mais la remontée se fait correctement

![2024-08-05 14_11_55-Aperçu – Home Assistant – Brave](https://github.com/user-attachments/assets/9b38e068-68f9-411f-ada8-ef2f05a95317)

**Comment by Link0Darck** [comment]
Moi je n'ai toujours rien alors j'ai refait la la clé de l'API

**Comment by Link0Darck** [comment]
c'est bon cela c'est rétablie de mon coter mais je pense investir dans un Eco joko pour voir en temps réelle et comparer avec ceux que Enedis relèves car j'ai de forte doute genre j'ai des pique alors que je suis pas chez moi 😂

**Comment by Link0Darck** [comment]
Par contre faudrait le créateur crée un système qui prévient si il y une maintenance cela serais bien je ne sais pas si c'est possible je suis jamais lancé sur de la création addon sur Home assistant
