### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by kevincaradant** [saniho/apiEnedis#25]
Hi

When I start HA, I got this issue, and no data is available :/ ( no entities)

```
home-assistant   | 2020-12-31 00:36:01 ERROR (MainThread) [homeassistant.config] Platform error: sensor
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/config/custom_components/myEnedis/myEnedis.py", line 6, in <module>
home-assistant   |     from . import  messages
home-assistant   | ImportError: cannot import name 'messages' from partially initialized module 'custom_components.myEnedis' (most likely due to a circular import) (/config/custom_components/myEnedis/__init__.py)
home-assistant   | 
home-assistant   | During handling of the above exception, another exception occurred:
home-assistant   | 
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/config.py", line 823, in async_process_component_config
home-assistant   |     platform = p_integration.get_platform(domain)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/loader.py", line 424, in get_platform
home-assistant   |     cache[full_name] = self._import_platform(platform_name)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/loader.py", line 429, in _import_platform
home-assistant   |     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
home-assistant   |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
home-assistant   |     return _bootstrap._gcd_import(name[level:], package, level)
home-assistant   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
home-assistant   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
home-assistant   |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
home-assistant   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
home-assistant   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
home-assistant   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
home-assistant   |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
home-assistant   |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
home-assistant   |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
home-assistant   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
home-assistant   |   File "/config/custom_components/myEnedis/__init__.py", line 17, in <module>
home-assistant   |     from . import myEnedis
home-assistant   |   File "/config/custom_components/myEnedis/myEnedis.py", line 8, in <module>
home-assistant   |     import messages
home-assistant   | ModuleNotFoundError: No module named 'messages'
```

![image](https://user-images.githubusercontent.com/6093175/103386795-cd37c700-4b00-11eb-9146-ef676716dad7.png)

![image](https://user-images.githubusercontent.com/6093175/103386845-096b2780-4b01-11eb-9146-68405db1b3e3.png)

In sensors.yaml:
```
#Linky
  - platform: myEnedis
    token: xxxx
    code: xxx
    scan_interval: 3600
    delay: 7200
```

Regards

**Comment by kevincaradant** [comment]
First try. I tried to rename directly in the `custom_components` folder, the `Messages.py` file into `messages.py`.

I suspect that you're using the plugin under Windows where the case sensitive is not a problem but under Linux like me it's an issue.
MAybe I'm wrong, I let you to say me what you think about this.

If I rename the file, I got an other issue 

```
home-assistant   | 2020-12-31 00:52:42 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up myEnedis platform for sensor
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
home-assistant   |     await asyncio.shield(task)
home-assistant   |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
home-assistant   |     result = self.fn(*self.args, **self.kwargs)
home-assistant   |   File "/config/custom_components/myEnedis/sensor.py", line 95, in setup_platform
home-assistant   |     add_entities([myEnedisSensor(session, name, update_interval, mSS )], True)
home-assistant   |   File "/config/custom_components/myEnedis/sensor.py", line 239, in __init__
home-assistant   |     self.update = Throttle( timedelta(seconds=interval))(self._update)
home-assistant   | TypeError: unsupported type for timedelta seconds component: datetime.timedelta
```
=> home-assistant   | TypeError: unsupported type for timedelta seconds component: datetime.timedelta

Don't know what is it

**Comment by saniho** [comment]
Hello please test with alpha version 6 and let me know...

**Comment by saniho** [comment]
Ihave mak in yourfirst message your private credential....

**Comment by kevincaradant** [comment]
OK I'm going to try it ASAP.

Don't worry it was a fake credential in my first message ')

**Comment by kevincaradant** [comment]
Still not good but better

I got this issue now:
```
home-assistant   | 2021-01-01 11:18:22 ERROR (SyncWorker_7) [custom_components.myEnedis.sensor] run myEnedis
home-assistant   | NoneType: None
```

![image](https://user-images.githubusercontent.com/6093175/103437083-2f88e880-4c23-11eb-9dbe-403cee0ce268.png)

**Comment by kevincaradant** [comment]
Since alpha 7 I got a string error ;)

![image](https://user-images.githubusercontent.com/6093175/103444019-fcffdf80-4c64-11eb-8b2c-ba473e28c0e9.png)

**Comment by pyzimmer** [comment]
Je viens également d'installer le plugin et il ne fonctionne pas, voici les logs au démarrage :

```
2021-01-03 22:53:03 ERROR (SyncWorker_2) [custom_components.myEnedis.sensor] run myEnedis
NoneType: None
2021-01-03 22:53:04 WARNING (SyncWorker_4) [custom_components.myEnedis.sensor] myEnedis err ('call', 'error', 'client_not_found')
2021-01-03 22:53:04 WARNING (SyncWorker_4) [custom_components.myEnedis.sensor] myEnedis ...390882291869 update lancé, status precedent : True, lastCall :None
2021-01-03 22:53:04 WARNING (SyncWorker_4) [custom_components.myEnedis.sensor] ------------------------------------------------------------
2021-01-03 22:53:04 WARNING (SyncWorker_4) [custom_components.myEnedis.sensor] Erreur inconnue call ERROR 'NoneType' object is not subscriptable
2021-01-03 22:53:04 WARNING (SyncWorker_4) [custom_components.myEnedis.sensor] Erreur last answer 'NoneType' object is not subscriptable
2021-01-03 22:53:04 WARNING (SyncWorker_4) [custom_components.myEnedis.sensor] Erreur last call 
2021-01-03 22:53:04 WARNING (SyncWorker_4) [custom_components.myEnedis.sensor] ------------------------------------------------------------
2021-01-03 22:53:04 WARNING (SyncWorker_4) [custom_components.myEnedis.sensor] (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x6ce86e48>)
2021-01-03 22:53:04 WARNING (SyncWorker_4) [custom_components.myEnedis.sensor] LastMethodCall :_ 
```


Je pense que c'est le même bug.
J'ai essayé d'installer chaque version , y compris les alpha, l'entité est toujours dans l'état  "unavailable"

**Comment by kevincaradant** [comment]
@saniho 

Hey it's me again.

I don't know what did you do on the lastest version but I got these errors until 5 minutes :)

```
home-assistant   | 2021-01-06 21:14:45 ERROR (MainThread) [myEnedis] yesteday sensor, _update_state
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:14:45 ERROR (MainThread) [myEnedis] state 3.06
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:14:45 ERROR (MainThread) [myEnedis] status_counts defaultdict(<class 'int'>, {'version': '1.1.1.0alpha1', 'yesterday_HC_cost': '1.779', 'yesterday_HP_cost': '1.277', 'daily_cost': '3.06'})
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:19:45 ERROR (MainThread) [myEnedis] yesteday 2021-01-05, lastYesterday 2021-01-05
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:19:45 ERROR (MainThread) [myEnedis] yesteday sensor, _update_state
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:19:45 ERROR (MainThread) [myEnedis] state 3.06
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:19:45 ERROR (MainThread) [myEnedis] status_counts defaultdict(<class 'int'>, {'version': '1.1.1.0alpha1', 'yesterday_HC_cost': '1.779', 'yesterday_HP_cost': '1.277', 'daily_cost': '3.06'})
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:24:45 ERROR (MainThread) [myEnedis] yesteday 2021-01-05, lastYesterday 2021-01-05
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:24:45 ERROR (MainThread) [myEnedis] yesteday sensor, _update_state
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:24:45 ERROR (MainThread) [myEnedis] state 3.06
home-assistant   | NoneType: None
home-assistant   | 2021-01-06 21:24:45 ERROR (MainThread) [myEnedis] status_counts defaultdict(<class 'int'>, {'version': '1.1.1.0alpha1', 'yesterday_HC_cost': '1.779', 'yesterday_HP_cost': '1.277', 'daily_cost': '3.06'})
home-assistant   | NoneType: None
```

**Comment by saniho** [comment]
the last version( v1.1.1.0 ) solve this issue

**Comment by pyzimmer** [comment]
Bonjour,
Je viens de tester votre nouvelle version 1.1.1.0 , cela ne fonctionne toujours pas, j'ai toujours les mêmes messages d'erreur :
J'ai même désinstallé et résinstallé le plugin, sans succès.
```
2021-01-08 09:37:34 ERROR (SyncWorker_1) [myEnedis] run myEnedis
NoneType: None
2021-01-08 09:37:34 WARNING (SyncWorker_2) [myEnedis] myEnedis err ('call', 'error', 'client_not_found')
2021-01-08 09:37:34 WARNING (SyncWorker_2) [myEnedis] myEnedis ...390882291869 update lancé, status precedent : True, lastCall :None
2021-01-08 09:37:34 WARNING (SyncWorker_2) [myEnedis] ------------------------------------------------------------
2021-01-08 09:37:34 WARNING (SyncWorker_2) [myEnedis] Erreur inconnue call ERROR 'NoneType' object is not subscriptable
2021-01-08 09:37:34 WARNING (SyncWorker_2) [myEnedis] Erreur last answer 'NoneType' object is not subscriptable
2021-01-08 09:37:34 WARNING (SyncWorker_2) [myEnedis] Erreur last call 
2021-01-08 09:37:34 WARNING (SyncWorker_2) [myEnedis] ------------------------------------------------------------
2021-01-08 09:37:34 WARNING (SyncWorker_2) [myEnedis] (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x6da36408>)
2021-01-08 09:37:34 WARNING (SyncWorker_2) [myEnedis] LastMethodCall : 
2021-01-08 09:37:52 ERROR (MainThread) [custom_components.hacs.factory] badguy99/octocost - Repository is archived.
```
