### ISSUE TITLE
sensor.myenedis not showing after installation

### ISSUE THREAD

**Issue by henrey** [saniho/apiEnedis#49]
Hi everyone, I have a problem...
After having installed the component as the procedure said (via HACS), it hasn't shown in the developper tools or in entitied list.
The component is well displayed in the integration list
![pb_myenedis](https://user-images.githubusercontent.com/20564343/108609500-97abad80-73ce-11eb-9182-4dba4dfed396.PNG)
I've configured it well, entering my token, code ...
After having restarted the server it doesn't show in the entity list.
But I thing that my configuration.yaml filt is not complete for the configuration of sensors. In it I only have
"
  
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'

"
Thanks for your help guys!

**Comment by saniho** [comment]
hi, nothing is needed in the configuration
enedis have some issue,( lost all agreement ), can you renewall your access on https://enedisgateway.tech/

**Comment by henrey** [comment]
Hi! thank you for your answer.
I renew my access to the gateway but I have the same problem.
Is it not an integration problem? Because I don't see the sensor in dev tools. As if HA doesn't recognize it

**Comment by saniho** [comment]
can you provide by private message your credential ?

**Comment by henrey** [comment]
> can you provide by private message your credential ?

Sorry I don't see how to send you a private message. On your profile I don't have this option.

**Comment by saniho** [comment]
voici mon mail : sanihogithub(at)gmail.com

**Comment by zod1986** [comment]
J'ai le même soucis voici le log d'erreur (core) :

2021-03-04 21:33:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration myEnedis which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-04 21:33:14 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'myEnedis'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'myEnedis'
2021-03-04 21:33:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-04 21:33:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-04 21:33:16 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 19329232894416 for myEnedis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/myEnedis/__init__.py", line 65, in async_setup_entry
    await coordinator.async_setup()
  File "/config/custom_components/myEnedis/__init__.py", line 207, in async_setup
    await self.hass.async_add_executor_job(self.update_MyEnedis)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/myEnedis/__init__.py", line 176, in update_MyEnedis
    hc_cost = float(self.config_entry.options.get(hc_cost_key, "0.0"))
ValueError: could not convert string to float: '0,085'

**Comment by saniho** [comment]
@zod1986 , la valeur doit etre indiquée avec des points et non des virgules
