### ISSUE TITLE
Unexpected error importing

### ISSUE THREAD

**Issue by roumano** [saniho/apiEnedis#61]
Salut, 
D'abord un grand merci pour ton travail ! 

sur mon assistant core, j'ai installer apiEnedis et content-card-linky

j'accede bien a mes données d'enedis 

mais j'ai des Unexpected error importing quand je redemarre HomeAssistant : 
* Unexpected error importing myEnedis/media_source.py
* Unexpected error importing myEnedis/logbook.py
* Unexpected error importing myEnedis/system_health.py
* Unexpected error importing myEnedis/group.py

Full log 
```
mars 24 21:45:00 rasp hass[435]: 2021-03-24 21:45:00 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing myEnedis/media_source.py
mars 24 21:45:00 rasp hass[435]: Traceback (most recent call last):
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process
mars 24 21:45:00 rasp hass[435]:     platform = integration.get_platform(platform_name)
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 499, in get_platform
mars 24 21:45:00 rasp hass[435]:     cache[full_name] = self._import_platform(platform_name)
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 504, in _import_platform
mars 24 21:45:00 rasp hass[435]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
mars 24 21:45:00 rasp hass[435]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
mars 24 21:45:00 rasp hass[435]:     return _bootstrap._gcd_import(name[level:], package, level)
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
mars 24 21:45:00 rasp hass[435]: ModuleNotFoundError: No module named 'custom_components.apiEnedis.media_source'
mars 24 21:45:00 rasp hass[435]: 2021-03-24 21:45:00 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing myEnedis/logbook.py
mars 24 21:45:00 rasp hass[435]: Traceback (most recent call last):
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process
mars 24 21:45:00 rasp hass[435]:     platform = integration.get_platform(platform_name)
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 499, in get_platform
mars 24 21:45:00 rasp hass[435]:     cache[full_name] = self._import_platform(platform_name)
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 504, in _import_platform
mars 24 21:45:00 rasp hass[435]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
mars 24 21:45:00 rasp hass[435]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
mars 24 21:45:00 rasp hass[435]:     return _bootstrap._gcd_import(name[level:], package, level)
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
mars 24 21:45:00 rasp hass[435]: ModuleNotFoundError: No module named 'custom_components.apiEnedis.logbook'
mars 24 21:45:00 rasp hass[435]: 2021-03-24 21:45:00 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing myEnedis/system_health.py
mars 24 21:45:00 rasp hass[435]: Traceback (most recent call last):
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process
mars 24 21:45:00 rasp hass[435]:     platform = integration.get_platform(platform_name)
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 499, in get_platform
mars 24 21:45:00 rasp hass[435]:     cache[full_name] = self._import_platform(platform_name)
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 504, in _import_platform
mars 24 21:45:00 rasp hass[435]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
mars 24 21:45:00 rasp hass[435]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
mars 24 21:45:00 rasp hass[435]:     return _bootstrap._gcd_import(name[level:], package, level)
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
mars 24 21:45:00 rasp hass[435]: ModuleNotFoundError: No module named 'custom_components.apiEnedis.system_health'
mars 24 21:45:00 rasp hass[435]: 2021-03-24 21:45:00 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing myEnedis/group.py
mars 24 21:45:00 rasp hass[435]: Traceback (most recent call last):
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process
mars 24 21:45:00 rasp hass[435]:     platform = integration.get_platform(platform_name)
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 499, in get_platform
mars 24 21:45:00 rasp hass[435]:     cache[full_name] = self._import_platform(platform_name)
mars 24 21:45:00 rasp hass[435]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 504, in _import_platform
mars 24 21:45:00 rasp hass[435]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
mars 24 21:45:00 rasp hass[435]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
mars 24 21:45:00 rasp hass[435]:     return _bootstrap._gcd_import(name[level:], package, level)
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mars 24 21:45:00 rasp hass[435]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
mars 24 21:45:00 rasp hass[435]: ModuleNotFoundError: No module named 'custom_components.apiEnedis.group'

```

**Comment by saniho** [comment]
Hello, comment as-tu fait l'installation ? via HACS ?

**Comment by roumano** [comment]
Non, c'était en manuel. Depuis j'ai installé Hacs, je peut regarder, si tu
veut, si j'installe via hacs si ça fait le même chose

**Comment by saniho** [comment]
yes, peux-tu voir ?

**Comment by roumano** [comment]
Pareil (en même temps, c'était la même version)

**Comment by saniho** [comment]
humm..c'est vraiement surprenant les erreurs, car rien à voir avec myEnedis ...
As-tu essayer de desintaller le compostant et de le reajouter ensuite ?
Sinon peut-etre un soucis plus avec ton home assistant...

**Comment by roumano** [comment]
Supprimer , redémarrer le service, réinstaller, redémarrer le service a résolu le souci.

Bizarre...

**Comment by dtrouillet** [comment]
Bonjour,

Avez-vous trouvé une solution? J'ai la même erreur (en manuel).

Damien
