### ISSUE TITLE
WARNING in HA Logs

### ISSUE THREAD

**Issue by Minims** [saniho/apiEnedis#67]
Hello, 
Is it possible to fix ?  It seems this will be a blocker in next HA release. 
https://github.com/home-assistant/core/pull/48387
 
```
myEnedis err I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/myEnedis/myEnedis.py, line 114: response = session.post(url, params=params, data=json.dumps(data), headers=headers, timeout=30)

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for myEnedis doing I/O at custom_components/myEnedis/myEnedis.py, line 114: response = session.post(url, params=params, data=json.dumps(data), headers=headers, timeout=30)
```

**Comment by saniho** [comment]
pourriez-vous tester avec la version 1.2.0.0rc1, attention, la config se fait uniquement avec la configuration ( et plus le YAML...bien penser à le desactiver )

**Comment by Minims** [comment]
Je viens de faire la mise à jour, mais j'ai cette erreur au démarrage de l'intégration après l'avoir configuré.
Je n'ai pas d'HC sur mon compteur et je n'ai pas coché HC dans l'intégration.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/myEnedis/__init__.py", line 117, in async_setup_entry
    await coordinator_enedis.async_setup()
  File "/config/custom_components/myEnedis/__init__.py", line 245, in async_setup
    await self.hass.async_add_executor_job(self.update_OptionsMyEnedis)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/myEnedis/__init__.py", line 220, in update_OptionsMyEnedis
    heurescreuses = eval(self.entry.options[HEURES_CREUSES])
KeyError: 'heures_creuses'
```

**Comment by saniho** [comment]
cela doit etre bok avec la derniere release : rc3, peux-tu tester ?

**Comment by saniho** [comment]
new test avec 1.2.0.0rc4 ?

**Comment by Minims** [comment]
C'est mieux. Nouvelle erreur, mais je ne sais pas si l'api Enedis est OK en ce moment

```
2021-05-11 22:29:09 ERROR (SyncWorker_1) [myEnedis] ************************************************************
2021-05-11 22:29:09 ERROR (SyncWorker_1) [myEnedis] header : {'Authorization': '*****', 'Content-Type': 'application/json', 'call-service': 'home-assistant-myEnedis', 'ha_sensor_myenedis_version': '1.2.0.0rc4'} 
2021-05-11 22:29:09 ERROR (SyncWorker_1) [myEnedis] params : None 
2021-05-11 22:29:09 ERROR (SyncWorker_1) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "********", "start": "2021-05-04", "end": "2021-05-11"} 
2021-05-11 22:29:09 ERROR (SyncWorker_1) [myEnedis] Error JSON : {"tag":"enedis_return_ko","error_code":"Internal Server error","description":"Un problème a été rencontré lors du traitement.","alert_user":true,"enedis_return":true,"support":"https://discord.gg/DfVJZme"} 
2021-05-11 22:29:09 ERROR (SyncWorker_1) [myEnedis] ************************************************************
2021-05-11 22:29:09 WARNING (SyncWorker_1) [myEnedis] ****** - Erreur call ERROR ('call', 'error', 'UNKERROR_001')
2021-05-11 22:29:09 WARNING (SyncWorker_1) [myEnedis] ****** - last call : updateLast7Days
```
