### ISSUE TITLE
plus d'entité sensor myEnedis+code

### ISSUE THREAD

**Issue by bran2000** [saniho/apiEnedis#7]
Bonjour,
suite à la dernière mise à jour, je n'ai plus le sensor myendis avec le code, j'ai tenté une réinstall du sensor, il n'apparait toujours pas, vous auriez une idée du problème ?
Merci

**Comment by bran2000** [comment]
Pour info, je viens de regarder dans les logs j'ai les erreurs suivantes :

2020-12-05 14:33:46 WARNING (SyncWorker_13) [custom_components.myEnedis.sensor] myEnedis version 1.0.4.0
2020-12-05 14:33:46 INFO (SyncWorker_13) [custom_components.myEnedis.sensor] --updateContract --
2020-12-05 14:33:47 INFO (SyncWorker_13) [custom_components.myEnedis.sensor] updateContract : data {'error': 'service_offline', 'description': 'Le service est temporaire Hors-Ligne', 'support': 'https://discord.com/invite/zXrr7ZV'}
2020-12-05 14:33:47 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up myEnedis platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/myEnedis/sensor.py", line 78, in setup_platform
myDataEnedis.updateContract()
File "/config/custom_components/myEnedis/apiEnedis.py", line 290, in updateContract
self.checkDataContract( data )
File "/config/custom_components/myEnedis/apiEnedis.py", line 403, in checkDataContract
raise Exception( 'call' , "error", dataAnswer['enedis_return']["error"] )
KeyError: 'enedis_return'

**Comment by bran2000** [comment]
service hors ligne du coup ?

**Comment by bran2000** [comment]
Merci vous pouvez clôturé

**Comment by jpreglat** [comment]
Bonsoir, j'ai le même problème. Comment l'avez vous corrigé ? Bonne soirée.

**Comment by bran2000** [comment]
J’ai attendu la et redémarrer en soirée mon hA mais le problème était général après je ne sais pas si ça a un rapport mais j’ai eu une mise à jour HACS et je l’ai faite également

**Comment by saniho** [comment]
pour information, problème chez Enedis, réparé hier soir, ce qui fait que aucune information n'était disponible
j'ai dans la prochaine version, geré ce cas, pour ne pas perdre le sensor, et meme qu'il soit créé au demarrage, meme si enedis ne répond pas.

**Comment by bran2000** [comment]
Super et merci pour votre travail !

**Comment by kweebix** [comment]
Bonjour même problème pour moi ce soir c'est global ?
