### ISSUE TITLE
bug beta 1.2.0.0rc1

### ISSUE THREAD

**Issue by foXaCe** [saniho/apiEnedis#73]
bonjour avec la beta 1.2.0.0rc1 j'ai une erreur

`Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.config_entries
Source: custom_components/myEnedis/__init__.py:220
Integration: MyEnedis (documentation)
First occurred: 9:41:49 (1 occurrences)
Last logged: 9:41:49

Error setting up entry 24202170679343 for myEnedis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/myEnedis/__init__.py", line 117, in async_setup_entry
    await coordinator_enedis.async_setup()
  File "/config/custom_components/myEnedis/__init__.py", line 245, in async_setup
    await self.hass.async_add_executor_job(self.update_OptionsMyEnedis)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/myEnedis/__init__.py", line 220, in update_OptionsMyEnedis
    heurescreuses = eval(self.entry.options[HEURES_CREUSES])
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
`

**Comment by saniho** [comment]
cela devrait etre ok avec la release : 1.2.0.0rc3.. on test

**Comment by saniho** [comment]
solved in 1.2.0.0rc4
