### ISSUE TITLE
Erreur Intégration - Failed to Setup , Check the logs

### ISSUE THREAD

**Issue by Shasdo** [saniho/apiEnedis#88]
HASS sur docker Synology
J'ai installé myEnedis Sensor via HACS sans problème particulier.

Après configuration de l'intégration (Token, PDL etc) l'intégration s'affiche avec l'erreur suivante en rouge:
"Failed to Setup , Check the logs"

Ci dessous les logs de l'erreur:

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/myEnedis/__init__.py:252
> Integration: MyEnedis (documentation)
> First occurred: 21:32:51 (1 occurrences)
> Last logged: 21:32:51
> 
> Error setting up entry XXCensuréXX for myEnedis
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/myEnedis/__init__.py", line 124, in async_setup_entry
>     await coordinator_enedis.async_setup()
>   File "/config/custom_components/myEnedis/__init__.py", line 312, in async_setup
>     await self.hass.async_add_executor_job(self.update_OptionsMyEnedis)
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/myEnedis/__init__.py", line 252, in update_OptionsMyEnedis
>     heurescreuses = eval(heurescreusesch)
>   File "<string>", line 1
>     [['00:00','07:00'],[['22:00','24:00']
> 
> SyntaxError: unexpected EOF while parsing

Est-ce dû à un compte Enedis trop récent?

**Comment by Shasdo** [comment]
Je viens de checker ce matin , le site enedis renvoi 

> Vous n'avez pas encore souscrit de service de partage de données avec Enedis ou un tiers.

Pourtant j'ai fais la procédure d'autorisation de collecte.

Je vais gratter de ce côté là.
