### ISSUE TITLE
Erreur: ModuleNotFoundError: No module named 'custom_components.apiEnedis.recorder'

### ISSUE THREAD

**Issue by vingerha** [saniho/apiEnedis#90]
Nouvelle installation, token et pdl bien installé, mais je recoit une erreur.
Neanmoins, des dates arrives

Logger: homeassistant.helpers.integration_platform
Source: loader.py:529
First occurred: 2:30:48 PM (5 occurrences)
Last logged: 2:30:48 PM

Unexpected error importing myEnedis/recorder.py
Unexpected error importing myEnedis/group.py
Unexpected error importing myEnedis/media_source.py
Unexpected error importing myEnedis/system_health.py
Unexpected error importing myEnedis/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 524, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 529, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.apiEnedis.recorder'

**Comment by saniho** [comment]
l'integration manuelle est depréciée, il ne faut utiliser que lintégration via HACS

**Comment by vingerha** [comment]
Merçi et peut-être enlever cette option de la documentation?
