### ISSUE TITLE
Quota de requêtes dépassé

### ISSUE THREAD

**Issue by mdeweerd** [saniho/apiEnedis#97]
Je salue le travail effectué (gateway, intégration, carte lovelace).

Toutefois je craignais un peu la fréquence des demandes, et voici ce que m'affiche la carte:
![image](https://user-images.githubusercontent.com/1504752/143506873-d233657f-0aef-454b-bd97-58d6d4ecb6bb.png)

Il faut savoir que j'ai deux compteurs sur mon compte ce qui augmente le nombre de requêtes mécaniquement.

Si j'en crois le message, le quota de Q4 est atteint, je retrouverai la fonctionnalité en janvier 2022.

J'active le débogue sur l'intégration, je crois qu'on obtient la réponse de l'API de cette manière - je partagerai s'il y a qqchse d'utile.

**Comment by saniho** [comment]
hello, le quota que tu vois est un bug de enedis qui revient reguièrement( ils corrigeront un jour  j'espère ).... mais il n'a rien à voir avec myEnedis, normalement quelques jours après tu ne l'as pu

**Comment by mdeweerd** [comment]
Ok, je verrai bien.

Voici ce que j'ai dans mes traces, j'ai remplacer les points de livraison et la clef secrete (j'ai deux PDL):
```
1-11-27 10:01:54 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2021-11-27 10:02:25 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2021-11-27 10:03:27 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2021-11-27 10:03:58 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2021-11-27 10:04:29 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2021-11-27 10:05:30 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2021-11-27 10:06:02 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2021-11-27 10:06:33 ERROR (SyncWorker_10) [myEnedis] ====== Appel http !!! requests.exceptions.Timeout
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] NUMERO_PDL2 - last call : updateLast7DaysDetails
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] myEnedis ...NUMERO_PDL2 update termine, on retentera plus tard(B)
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] ------------------------------------------------------------
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] Erreur inconnue call ERROR 'meter_reading'
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] Erreur last answer 'meter_reading'
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] Erreur last call updateLast7DaysDetails
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] Erreur last answer {'enedis_return': {'error': 'UNKERROR_002', 'message': 'Timeout'}}
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] Traceback (most recent call last):
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 778, in update
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 336, in updateLast7DaysDetails
  File "/config/custom_components/myEnedis/myDataEnedisByDayDetail.py", line 108, in updateData
  File "/config/custom_components/myEnedis/myDataEnedisByDayDetail.py", line 146, in createMultiDaysHCHP
  File "/config/custom_components/myEnedis/myClientEnedis.py", line 844, in update
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] ------------------------------------------------------------
2021-11-27 10:07:03 WARNING (SyncWorker_10) [myEnedis] (<class 'Exception'>, Exception(KeyError('meter_reading')), <traceback object at 0x7f44a9be0f80>)
2021-11-27 10:07:03 ERROR (SyncWorker_10) [myEnedis] LastMethodCall : updateLast7DaysDetails
2021-11-27 22:13:36 ERROR (MainThread) [custom_components.hacs] saniho/apiEnedis - GitHub returned 500 for https://api.github.com/repos/saniho/apiEnedis/branches/main
2021-11-28 09:38:02 ERROR (SyncWorker_7) [myEnedis] myEnedis(1.3.1.14) ...NUMERO_PDL update lanc.., status precedent : True, lastMethodCall :None, forcejson :False
2021-11-28 09:38:06 ERROR (SyncWorker_7) [myEnedis] ************************************************************
2021-11-28 09:38:06 ERROR (SyncWorker_7) [myEnedis] header : {'Authorization': 'CLEF_AUTHENTICATION', 'Content-Type': 'application/json', 'call
2021-11-28 09:38:06 ERROR (SyncWorker_7) [myEnedis] params : None
2021-11-28 09:38:06 ERROR (SyncWorker_7) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "NUMERO_PDL", "start": "2021-11-27", "end": "2021-11-28"}
2021-11-28 09:38:06 ERROR (SyncWorker_7) [myEnedis] Error JSON : {"usage_point_id":"NUMERO_PDL","error":"token_refresh_401","description":"Une erreur est survenue, merci de r
2021-11-28 09:38:06 ERROR (SyncWorker_7) [myEnedis] ************************************************************
2021-11-28 09:38:56 ERROR (SyncWorker_7) [myEnedis] myEnedis(1.3.1.14) ...NUMERO_PDL update termine, status courant : True, lastCall :None, nbCall :12
2021-11-28 09:57:03 ERROR (SyncWorker_2) [myEnedis] myEnedis(1.3.1.14) ...NUMERO_PDL2 update lanc.., status precedent : False, lastMethodCall :None, forcejson :False
2021-11-28 10:00:10 ERROR (SyncWorker_2) [myEnedis] ************************************************************
2021-11-28 10:00:10 ERROR (SyncWorker_2) [myEnedis] header : {'Authorization': 'CLEF_AUTHENTICATION', 'Content-Type': 'application/json', 'call
2021-11-28 10:00:10 ERROR (SyncWorker_2) [myEnedis] params : None
2021-11-28 10:00:10 ERROR (SyncWorker_2) [myEnedis] data : {"type": "daily_consumption", "usage_point_id": "NUMERO_PDL2", "start": "2020-11-16", "end": "2020-11-22"}
2021-11-28 10:00:10 ERROR (SyncWorker_2) [myEnedis] Error JSON : {"tag":"enedis_return_ko","error_code":"429","description":"Quota Q3 reached. Call threshold allowed on -1:-54:-2
2021-11-28 10:00:10 ERROR (SyncWorker_2) [myEnedis] ************************************************************
2021-11-28 10:00:10 ERROR (SyncWorker_2) [myEnedis] NUMERO_PDL2 - Erreur call ERROR ('call', 'error', '429')
2021-11-28 10:00:10 ERROR (SyncWorker_2) [myEnedis] NUMERO_PDL2 - last call : updateCurrentWeekLastYear
2021-11-28 10:00:10 ERROR (SyncWorker_2) [myEnedis] myEnedis ...NUMERO_PDL2 update termine, on retentera plus tard(A)
```

**Comment by mdeweerd** [comment]
Juste pour info, même si j'ai eu ce jour des types de réponse "Quota Q3 reached", les données ont bien été récupérés au final ;-).

```json
{"tag":"enedis_return_ko","error_code":"429","description":"Quota Q3 reached. Call threshold allowed on -7:-10:-38","alert_user":true,"enedis_return":true,"support":"https://discord.gg/DfVJZme"}
```

```json
{"tag":"enedis_return_ko","error_code":"429","description":"Quota Q3 reached. Call threshold allowed on -8:-37:-29","alert_user":true,"enedis_return":true,"support":"https://discord.gg/DfVJZme"}
```
